CREATE TABLE Source
(
	solution_id bigint NOT NULL,
	source_id bigint NOT NULL,
	random_index bigint NOT NULL,
	ref_epoch float NOT NULL,
	ra float NOT NULL,
	ra_error float NOT NULL,
	dec float NOT NULL,
	dec_error float NOT NULL,
	parallax float NULL,
	parallax_error float NULL,
	pmra float NULL,
	pmra_error real NULL,
	pmdec float NULL,
	pmdec_error float NULL,
	ra_dec_corr real NOT NULL,
	ra_parallax_corr real NULL,
	ra_pmra_corr real NULL,
	ra_pmdec_corr real NULL,
	dec_parallax_corr real NULL,
	dec_pmra_corr real NULL,
	dec_pmdec_corr real NULL,
	parallax_pmra_corr real NULL,
	parallax_pmdec_corr real NULL,
	pmra_pmdec_corr real NULL,
	astrometric_n_obs_al int NOT NULL,
	astrometric_n_obs_ac int NOT NULL,
	astrometric_n_good_obs_al int NOT NULL,
	astrometric_n_good_obs_ac int NOT NULL,
	astrometric_n_bad_obs_al int NOT NULL,
	astrometric_n_bad_obs_ac int NOT NULL,
	astrometric_delta_q float NULL,
	astrometric_excess_noise float NOT NULL,
	astrometric_excess_noise_sig float NOT NULL,
	astrometric_primary_flag varchar(5) NOT NULL,	-- ********
	astrometric_relegation_factor real NOT NULL,
	astrometric_weight_al real NULL,
	astrometric_weight_ac real NULL,
	astrometric_priors_used int NOT NULL,
	matched_observations smallint NOT NULL,
	duplicated_source varchar(5) NOT NULL,			-- ********
	scan_direction_strength_k1 real NOT NULL,
	scan_direction_strength_k2 real NOT NULL,
	scan_direction_strength_k3 real NOT NULL,
	scan_direction_strength_k4 real NOT NULL,
	scan_direction_mean_k1 real NOT NULL,
	scan_direction_mean_k2 real NOT NULL,
	scan_direction_mean_k3 real NOT NULL,
	scan_direction_mean_k4 real NOT NULL,
	phot_g_n_obs int NOT NULL,
	phot_g_mean_flux float NOT NULL,
	phot_g_mean_flux_error float NOT NULL,
	phot_g_mean_mag float NOT NULL,
	phot_variable_flag varchar(50) NULL,
	l float NOT NULL,
	b float NOT NULL,
	ecl_lon float NOT NULL,
	ecl_lat float NOT NULL
)