CREATE DATABASE [SkyNode_SDSSDR13]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRIMARY_0', FILENAME = N'C:\Data\SSD_A\SSD0\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_0.mdf' , SIZE = 68608000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_1', FILENAME = N'C:\Data\SSD_A\SSD1\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_1.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_2', FILENAME = N'C:\Data\SSD_A\SSD2\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_2.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_3', FILENAME = N'C:\Data\SSD_A\SSD3\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_3.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_4', FILENAME = N'C:\Data\SSD_A\SSD4\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_4.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_5', FILENAME = N'C:\Data\SSD_A\SSD5\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_5.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_6', FILENAME = N'C:\Data\SSD_A\SSD6\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_6.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PRIMARY_7', FILENAME = N'C:\Data\SSD_A\SSD7\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PRIMARY_7.ndf' , SIZE = 81920000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [PHOTOIDX] 
( NAME = N'PHOTOIDX_0', FILENAME = N'C:\Data\SSD_A\SSD0\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_0.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_1', FILENAME = N'C:\Data\SSD_A\SSD1\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_1.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_2', FILENAME = N'C:\Data\SSD_A\SSD2\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_2.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_3', FILENAME = N'C:\Data\SSD_A\SSD3\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_3.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_4', FILENAME = N'C:\Data\SSD_A\SSD4\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_4.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_5', FILENAME = N'C:\Data\SSD_A\SSD5\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_5.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_6', FILENAME = N'C:\Data\SSD_A\SSD6\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_6.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOIDX_7', FILENAME = N'C:\Data\SSD_A\SSD7\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOIDX_7.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [PHOTOOBJ] 
( NAME = N'PHOTOOBJ_0', FILENAME = N'C:\Data\SSD_A\SSD0\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_0.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_1', FILENAME = N'C:\Data\SSD_A\SSD1\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_1.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_2', FILENAME = N'C:\Data\SSD_A\SSD2\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_2.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_3', FILENAME = N'C:\Data\SSD_A\SSD3\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_3.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_4', FILENAME = N'C:\Data\SSD_A\SSD4\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_4.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_5', FILENAME = N'C:\Data\SSD_A\SSD5\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_5.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_6', FILENAME = N'C:\Data\SSD_A\SSD6\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_6.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0),
( NAME = N'PHOTOOBJ_7', FILENAME = N'C:\Data\SSD_A\SSD7\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\PHOTOOBJ_7.ndf' , SIZE = 153600000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'LOG_0', FILENAME = N'C:\Data\SSD_A\SSD0\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_0.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_1', FILENAME = N'C:\Data\SSD_A\SSD1\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_1.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_2', FILENAME = N'C:\Data\SSD_A\SSD2\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_2.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_3', FILENAME = N'C:\Data\SSD_A\SSD3\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_3.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_4', FILENAME = N'C:\Data\SSD_A\SSD4\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_4.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_5', FILENAME = N'C:\Data\SSD_A\SSD5\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_5.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_6', FILENAME = N'C:\Data\SSD_A\SSD6\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_6.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0), 
( NAME = N'LOG_7', FILENAME = N'C:\Data\SSD_A\SSD7\Graywulf\SkyQuery\SDSSDR13\FULL\PROD\SkyNode_SDSSDR13\LOG_7.ldf' , SIZE = 20480000KB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

ALTER DATABASE [SkyNode_SDSSDR13] SET RECOVERY SIMPLE 
GO
