WITH q AS
(
	SELECT *, ROW_NUMBER() OVER (PARTITION BY source_id ORDER BY source_id) rn
	FROM GaiaDR1_Load.dbo.Source
)
INSERT INTO [SkyNode_GAIADR1].[dbo].[Source] WITH (TABLOCKX)
           ([solution_id]
           ,[source_id]
           ,[random_index]
           ,[ref_epoch]
           ,[ra]
           ,[ra_error]
           ,[dec]
           ,[dec_error]
		   ,[cx]
		   ,[cy]
		   ,[cz]
		   ,[htmid]
		   ,[zoneid]
           ,[parallax]
           ,[parallax_error]
           ,[pmra]
           ,[pmra_error]
           ,[pmdec]
           ,[pmdec_error]
           ,[ra_dec_corr]
           ,[ra_parallax_corr]
           ,[ra_pmra_corr]
           ,[ra_pmdec_corr]
           ,[dec_parallax_corr]
           ,[dec_pmra_corr]
           ,[dec_pmdec_corr]
           ,[parallax_pmra_corr]
           ,[parallax_pmdec_corr]
           ,[pmra_pmdec_corr]
           ,[astrometric_n_obs_al]
           ,[astrometric_n_obs_ac]
           ,[astrometric_n_good_obs_al]
           ,[astrometric_n_good_obs_ac]
           ,[astrometric_n_bad_obs_al]
           ,[astrometric_n_bad_obs_ac]
           ,[astrometric_delta_q]
           ,[astrometric_excess_noise]
           ,[astrometric_excess_noise_sig]
           ,[astrometric_primary_flag]
           ,[astrometric_relegation_factor]
           ,[astrometric_weight_al]
           ,[astrometric_weight_ac]
           ,[astrometric_priors_used]
           ,[matched_observations]
           ,[duplicated_source]
           ,[scan_direction_strength_k1]
           ,[scan_direction_strength_k2]
           ,[scan_direction_strength_k3]
           ,[scan_direction_strength_k4]
           ,[scan_direction_mean_k1]
           ,[scan_direction_mean_k2]
           ,[scan_direction_mean_k3]
           ,[scan_direction_mean_k4]
           ,[phot_g_n_obs]
           ,[phot_g_mean_flux]
           ,[phot_g_mean_flux_error]
           ,[phot_g_mean_mag]
           ,[phot_variable_flag]
           ,[l]
           ,[b]
           ,[ecl_lon]
           ,[ecl_lat])
SELECT 
		   [solution_id]
           ,[source_id]
           ,[random_index]
           ,[ref_epoch]
           ,[ra]
           ,[ra_error]
           ,[dec]
           ,[dec_error]
		   ,c.x AS  [cx]
		   ,c.y AS [cy]
		   ,c.z AS [cz]
		   ,SkyQuery_CODE.htmid.FromXyz(c.x,c.y,c.z) AS [htmid]
		   ,SkyQuery_CODE.skyquery.ZoneIDFromDec(dec,4.0/3600.00000000) as [zoneid]
           ,[parallax]
           ,[parallax_error]
           ,[pmra]
           ,[pmra_error]
           ,[pmdec]
           ,[pmdec_error]
           ,[ra_dec_corr]
           ,[ra_parallax_corr]
           ,[ra_pmra_corr]
           ,[ra_pmdec_corr]
           ,[dec_parallax_corr]
           ,[dec_pmra_corr]
           ,[dec_pmdec_corr]
           ,[parallax_pmra_corr]
           ,[parallax_pmdec_corr]
           ,[pmra_pmdec_corr]
           ,[astrometric_n_obs_al]
           ,[astrometric_n_obs_ac]
           ,[astrometric_n_good_obs_al]
           ,[astrometric_n_good_obs_ac]
           ,[astrometric_n_bad_obs_al]
           ,[astrometric_n_bad_obs_ac]
           ,[astrometric_delta_q]
           ,[astrometric_excess_noise]
           ,[astrometric_excess_noise_sig]
           ,CAST(CASE WHEN [astrometric_primary_flag] = 'true' THEN 1 ELSE 0 END AS bit) AS [astrometric_primary_flag]
           ,[astrometric_relegation_factor]
           ,[astrometric_weight_al]
           ,[astrometric_weight_ac]
           ,[astrometric_priors_used]
           ,[matched_observations]
           ,CAST(CASE WHEN [duplicated_source] = 'true' THEN 1 ELSE 0 END AS bit) AS [duplicated_source]
           ,[scan_direction_strength_k1]
           ,[scan_direction_strength_k2]
           ,[scan_direction_strength_k3]
           ,[scan_direction_strength_k4]
           ,[scan_direction_mean_k1]
           ,[scan_direction_mean_k2]
           ,[scan_direction_mean_k3]
           ,[scan_direction_mean_k4]
           ,[phot_g_n_obs]
           ,[phot_g_mean_flux]
           ,[phot_g_mean_flux_error]
           ,[phot_g_mean_mag]
           ,[phot_variable_flag]
           ,[l]
           ,[b]
           ,[ecl_lon]
           ,[ecl_lat]
FROM q
CROSS APPLY SkyQuery_CODE.point.EqToXyz(ra, dec) AS c
WHERE q.rn = 1